
  CREATE TABLE "SYSTEM"."USER_DETAILS" 
   (	"EMAIL" CHAR(40 BYTE), 
	"NAME" CHAR(50 BYTE), 
	"PASSWORD" CHAR(30 BYTE), 
	"DOB" DATE, 
	"PHNO" CHAR(13 BYTE), 
	"ADDRESS" CHAR(100 BYTE), 
	"CITY" CHAR(30 BYTE), 
	"STATE" CHAR(30 BYTE), 
	 PRIMARY KEY ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
